### ISSUE TITLE
Failing to connect to OVMS after running ~5 pipelines

### ISSUE THREAD

**Issue by antoniomtz** [intel-retail/automated-self-checkout#331]
## Version

main

## Hardware configuration

List Hardware components used. 
Ex. 
Issue found with the following:
- Intel® xeon Platinum 8351N with Intel® Data Center GPU Flex 140
- 12th Gen Intel® Core™ i7 with Intel® Arc™ A770M Graphics

## Describe the bug

After running 5 pipelines (object_detection or any other), the consequent pipelines cannot connect to OVMS.

The following error appear on the results log: 

> RuntimeError: Requested model: ssd_mobilenet_v1_coco, version: latest, has not been found or is not in available state

It appears to be a race condiction. There is a fix when increasing the InitWaitTime to 20s.

## To Reproduce

1. run camera simulator
2. run 5 or more pipelines:
DEVICE=CPU PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo -E ./run.sh --workload ovms --platform dgpu.0 --inputsrc rtsp://127.0.0.1:8554/camera_0
3. observe results logs and after 5 pipelines, the rest of them will fail.

**Comment by jim-wang-intel** [comment]
notes:
- based on the error log, this issue seems to relate to the readiness of models from OpenVINO model server instance that is used for the pipeline application
- more pipelines launched, the system resource is more consumed and thus the launching time for OVMS server takes longer and hence the readiness of the model takes also longer

**Comment by vli11** [comment]
number of pipelines to run successfully can depend on user's system capability.
